DELIMITER $$
CREATE DEFINER=`root`@`%` PROCEDURE `FIND_PERSON`(IN p_person INT)
BEGIN
	SELECT * FROM person WHERE id_persona = p_person;
END$$
DELIMITER ;



DELIMITER $$
CREATE DEFINER=`root`@`%` PROCEDURE GET_TOTAL_PERSONS(OUT count_out INT)
BEGIN
	SELECT COUNT(*) into count_out FROM person;
END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`%` PROCEDURE DELETE_PERSON(IN P_ID_PERSONA INT)
BEGIN
	DELETE FROM person WHERE ID_PERSONA = P_ID_PERSONA;
END$$
DELIMITER ;



USE `springmysql`;
DROP function IF EXISTS `GET_NAME`;

DELIMITER $$
USE `springmysql`$$
CREATE FUNCTION GET_NAME ( P_PERSON_ID INT)
RETURNS varchar(200)
BEGIN
	DECLARE P_NAME VARCHAR(200);
    SELECT nombre into P_NAME from person where id_persona = P_PERSON_ID;
    RETURN P_NAME;
END$$

DELIMITER ;

